### ISSUE TITLE
How to change the flakes for musical notes? [Query]

### ISSUE THREAD

**Issue by juanamm** [hcodes/snowflakes#36]
First of all I want to thank you for creating this excellent tool, I always use it on my website at Christmas.

At the moment I am using `snowflakes.min.js` invoking it from HTML.

Since I have a website where I share music, I came up with the idea of ​​being able to use your tool all year round (not just at Christmas) by changing the flakes for different musical notes. 

I have little knowledge of JS but no knowledge of SVG or XML. 

How could `background-image `used in the `snowflakes.min.js`  file be modified to replace the flakes with musical notes?

I hope I have not offended or bothered you by making this query.

Happy New Year

**Comment by hcodes** [comment]
```css
.snowflakes .snowflake__inner {
    background-image: url('./my_path/my_image.png')
}
```
